# fly.toml app configuration file generated for realapp1 on 2026-06-09T05:30:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'realapp1'
primary_region = 'bom'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
